config/routes.rb
Rails.application.routes.draw do
  resources :photos
  #get 'photo/index'

  devise_for :users
  get 'home/create'
  root 'photos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord

  belongs_to :user

  validates :title, presence: true, uniqueness: true
  validates :body, presence: true, length: {minimum:10}
  before_create :set_visits_count

  enum status: [:publico, :privado, :compartido]

  has_attached_file :cover, styles: {medium: "800x600", thu:"100x50"}
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/

  def update_visits_count
    #self.save if self.visit_count.nil?
    self.update(visit_count: self.visit_count + 1)
  end

  private
  def set_visits_count
    self.visit_count ||=0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 #Trae la keyword y la busca en Photo, después comprueba si se encuentra algun
 #usuario con la sesión iniciada de ser así, solo busca las publicaciones
 #compartidas, publicas y privadas si este usuario cuenta con dichas
 #publicaciones. Si no han iniciado sesión solo se buscan las publicaciones
 #publicas, luego lo que hace es responder buscando el archivo con la
 #extensión js.
  def create
    word = "%#{params[:keyword]}%"
    @pho = Photo.where("title LIKE ? OR body LIKE ?",word,word)

    if user_signed_in?

      @pho.each do |p|
        puts p
        n = p.status
        if  p.user_id == current_user.id || n == "compartido" || n== "publico"
          @photos = p
        end

      end
    else
      @pho.each do |p|
        n = p.status
        if n == "publico"
          @photos = p
        end
      end
    end
    #@photos = Photo.where("title LIKE ? OR body LIKE ? AND status = ?",word,word,0)

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, except: [:show,:index]

  def index
    @photos = Photo.all
    if user_signed_in?
      # @photos.each do |p|
      #   if current_user.id == p.user_id
      #     @photo = p
      #   end
      #   n = p.status
      #   if n == "publico" || n == "compartido"
      #     @photo = p
      #     puts "enttro a atupoeh"
      #   end
      # end
      # @photos = @photo
      #
      @po = Photo.where('status = ? OR status = ? OR user_id = ?', 2,0, current_user.id)
      @photos = @po

    else
      @po1 = Photo.where('status = ?', 0)
      @photos = @po1
    end

  end

  def show
    @photo = Photo.find(params[:id])
    @photo.update_visits_count
  end

  def new
    @photo = Photo.new
    @statuses = Photo.statuses
  end

  def edit
    @photo = Photo.find(params[:id])
    @statuses = Photo.statuses
    if current_user.id == @photo.user_id
      puts "Puede editar"
    else
      redirect_to @photo
    end
  end

  def create
    @photo = current_user.photos.new(photo_params)
    if @photo.save
      redirect_to @photo
    else
      render :new
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    if current_user.id == @photo.user_id
      @photo.destroy
      redirect_to photos_path
    end

  end

  def update

      @photo = Photo.find(params[:id])
      @statuses = Photo.statuses
      if @photo.update(photo_params)
        redirect_to @photo
      else
        render :edit
      end
  end

  private
  def photo_params
    params.require(:photo).permit(:title,:body,:status, :cover)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imagine</title>
    <%= csrf_meta_tags %>
    <!-- Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <!-- Optional bootstrap theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah|Indie+Flower|Sedgwick+Ave+Display" rel="stylesheet">
  </head>

  <body>
    <%= render "partials/navigation" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/partials/_navigation.html.erb
<header>



  <nav class="be-black white large-padding">

<!--
    <div class="container-fluid">
      <div class="navbar-header">
        <h1 class="font" id="logo"> IMAGINE </h1>
      </div>

      <div class="container-fluid">
 -->

      <ul class="no-list row center-xs middle-xs font-navagation">
        <li class="col-md">
          <h1 class="no-margin" id="logo"> <%= link_to "IMAGINE", photos_path %></h1>
        </li>
        <% if user_signed_in?%>
          <li class="col-md"><%= link_to  new_photo_path do %>
            <span class="glyphicon glyphicon-pushpin "></span> Crear artículo<%end%>
          </li>
          <li class="col-md"><%= link_to  edit_user_registration_path do %>
            <span class="glyphicon glyphicon-user"></span> Usuario <%end%>
          </li>
          <li class="col-md"><%= link_to  destroy_user_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-log-in "></span> Cerrar sesión<%end%>
          </li>

        <%else%>
        <li class="col-md"><%= link_to  new_user_registration_path do %>
          <span class="glyphicon glyphicon-user"></span> Registrarse<%end%>
        </li>
        <li class="col-md"><%= link_to  new_user_session_path do %>
          <span class="glyphicon glyphicon-log-in"></span> Iniciar sesión<%end%>
        </li>

        <%end%>
      </ul>

      </div>
    </div>
  </nav>

</header>

app/views/photos/_form.html.erb
<%= form_for @photo do |f|%>
  <% @photo.errors.full_messages.each do |message| %>
    <div>
      <%= message %>
    </div>
  <% end %>
  <div class="field2">
    <%= label_tag( "Imagen de la publicación") %><br />
    <div class="field">
      <%=f.file_field :cover, placeholder: "Imagen", class:"font-button btn let be-black"%>
    </div>
  </div>
  <div class="field">
    <%= label_tag(:title, "Título de la publicación") %><br />
    <%=f.text_field :title, placeholder: "Título", class:"form-control"%>
  </div>
  <div class="field">
    <%= label_tag(:body, "Contenido") %><br />
    <%= f.text_area :body, placeholder: "Contenido de la publicación", style:"height:250px;", class:"form-control"%>
  </div>

  <div class="row">
     <div class="col-xs-12 form-group">
       <%= f.label :status %>
       <%= f.select :status, options_for_select(@statuses.collect { |s| [s[0].humanize, s[0]] }, selected: @photo.status), {} , class: "form-control" %>
     </div>
   </div>

  <div class="actions field center font-button">
    <%= f.submit "Publicar", class: "btn let be-black" %>
  </div>
<%end%>

app/views/photos/_photo.html.erb
<div class="col-md-8 col-md-offset-2 font-conten">
  <div class="container">
    <div class="field">
      <h1 class="font-title"><strong> <%= link_to photo.title, photo %> </strong> </h1>
    </div>
    <div class="field font-conten", style="text-align: left;">
      <%= photo.body%>
    </div>
    <div class="field font-conten", style="text-align: left;">
      <strong>Estado:</strong>
      <%= photo.status.humanize%>
    </div>
  </div>
</div>

app/views/photos/edit.html.erb
<div class="col-md-8 col-md-offset-2 font-conten">
  <div class="row">
    <h1 class="font-title"> <strong>  Editar artículo</strong></h1>
  </div>

  <%= render "form"%>

</div>

app/views/photos/index.html.erb
<div class="field">
  <%= form_tag "home/create", method: :get, remote: true, id:"search-form", class:"center font-content" do%>
    <%= text_field_tag :keyword, nil, placeholder: "Buscar por..."  %>
    <%= content_tag :button, type: :submit, class:"btn be-black white font-button" do%>
    Buscar
    <%end%>
  <%end%>
</div>


<div class="col-md-8 col-md-offset-2 font-conten">
  <div class="row">
    <h1 class="font-title"> <strong>Publicaciones</strong></h1>
  </div>
  <div class="row">
    <div class="field">
      <div id="respuesta">
      </div>
    </div>
    <p class="center">-----------------------------------------</p><br>
  </div>

  <div class="row">
    <% if user_signed_in? %>
      <h1 class="font-conten"> Bienvenido <%= current_user.email %></h1>
    <% end %>
    <p class="center">-----------------------------------------</p><br>
  </div>
  <div class="col-md-10 col-md-offset-1">
    <% @photos.each do |photo|%>
      <% if photo.cover? %>
        <div class=" gallery field font-conten", style="text-align: left;">
          <%= image_tag photo.cover.url() %>
        </div>
      <% else %>
        <div class=" gallery field font-conten", style="text-align: left;">
          <%= image_tag "imgdefault.jpg" %>
        </div>
      <% end %>
      <div class="field center">
        <h1 class="font-conten"><strong> <%= link_to photo.title, photo %> </strong> </h1>
      </div>
      <div class="field font-conten", style="text-align: left;">
        <%= photo.body%>
      </div>
      <div class="field font-conten", style="text-align: left;">
        <strong>Estado:</strong>
        <%= photo.status.humanize%>
      </div>
      <div id="ellink", class="filed font-button center">
        <% if user_signed_in? %>
          <%= link_to "Eliminar", photo, class:"btn be-black", method: :delete %>
        <% end %>
      </div>
      <p>-----------------------------------------</p><br>
    <%end%>
  </div>
</div>

app/views/photos/new.html.erb
<div class="col-md-8 col-md-offset-2 font-conten">
  <div class="row">
    <h1 class="font-title"> <strong>  Crear artículo</strong></h1>
  </div>

  <%= render "form"%>

</div>

app/views/photos/show.html.erb
<div class="col-md-8 col-md-offset-2 font-conten">
  <div class="row center">
    <h1 class="font-title"> <strong><%= @photo.title %></strong></h1>
  </div>
  <% if @photo.cover? %>
    <div class=" gallery field font-conten", style="text-align: left;">
      <%= image_tag @photo.cover.url() %>
    </div>
  <% else %>
    <div class=" gallery field font-conten", style="text-align: left;">
      <%= image_tag "imgdefault.jpg" %>
    </div>
  <% end %>
  <div class="container">
    <div class="field font-conten", style="text-align: left;">
      <% unless @photo.user.nil? %>
        <strong>Creado por:</strong> <%= @photo.user.email%>
      <%end%>
    </div>
    <div class="field font-conten", style="text-align: left;">
      <strong>Visitas:</strong>
      <%= @photo.visit_count%>
    </div>
    <div class="field font-conten", style="text-align: left;">
      <strong>Estado:</strong>
      <%= @photo.status.humanize%>
    </div>
    <div class="field font-conten", style="text-align: left;">
      <%= @photo.body%>
    </div>
    <div class="field2">
      <div id="ellink", class="filed font-button center">
        <%= link_to "Editar", edit_photo_path(@photo), class:"btn be-black" %>
      </div>
    </div>


  </div>

</div>